// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRvbO_K-Ts7lnihDcjQbFEcnzFeonKqWw',
    appId: '1:386920527201:web:5b2b58492dbd27a6dac120',
    messagingSenderId: '386920527201',
    projectId: 'doubles-4dc90',
    authDomain: 'doubles-4dc90.firebaseapp.com',
    storageBucket: 'doubles-4dc90.firebasestorage.app',
    measurementId: 'G-QBTBF569Z9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtyPRt12ny_pa6DKdb4GJUBHllg-PA9yg',
    appId: '1:386920527201:android:9e0c1d10c68f1992dac120',
    messagingSenderId: '386920527201',
    projectId: 'doubles-4dc90',
    storageBucket: 'doubles-4dc90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMDNy0JcO5Jh8shlKGWEns6D-Wn_a7G_c',
    appId: '1:386920527201:ios:d00984e75b9a9d58dac120',
    messagingSenderId: '386920527201',
    projectId: 'doubles-4dc90',
    storageBucket: 'doubles-4dc90.firebasestorage.app',
    iosBundleId: 'com.marriageconversation.doubles',
  );
}
